### ISSUE TITLE
SignalRCore: Deserializing complex objects in arguments (LitJSON)

### ISSUE THREAD

**Issue by xwipeoutx** [Benedicht/BestHTTP_Examples#2]
I'm sending a message with a more complex argument from SignalR Core into this library, every time the values of the complex type are just set to default.

This is using your example LitJson encoder, SignalRCore.

A very simple example below - this isn't using SignalR Core, but is replicating the argument serialization behaviour:

```
public class SomeObject
{
    public int someField;
}
```

```
public void TestRoundTripArgs()
{
    var enc = new LitJsonEncoder();

    var testArgs = new object[] {new SomeObject {someField = 2}};
    var jsonForArgs = JsonMapper.ToJson(testArgs);
    var returnValueForArgs = JsonMapper.ToObject<object[]>(jsonForArgs);
    var finalObj = (SomeObject)enc.ConvertTo(typeof(SomeObject), returnValueForArgs[0]);
    
    Debug.Log("Did some field persist? " + (finalObj.someField == 2));
}
```

So, A message signature like `SomeMessageReceived(SomeObject arg)` will always have `arg.someField` as `0`.

Delving into it, I've noticed the the message handling essentially deserialises arguments into an `object[]`, and then when it figures out the specific signature, it "clones" them into the concrete types from the message signature.  There's is an attempt in `JsonMapper` to force it to `Dictionary<string, object>` (presumably this was you?) in the initial deserialize if the value_type is `object`, but this doesn't work properly.

I'll raise a PR in a sec to work around it, but I'm unsure on the ramifications of it, is it's an upstream `JsonMapper` issue which seems to already have some custom handling for it.

**Comment by Benedicht** [comment]
Thanks for the report! Found and fixed it about a week ago similarly. I have a few additions to LitJson like the `Dictionary<string, object>` one.
