### ISSUE TITLE
HttpUpdateDelegator.SetThreadingMode doen't update IsThreaded

### ISSUE THREAD

**Issue by israellot** [Benedicht/BestHTTP_Examples#5]
IsThreaded property is not updated when changing the threading mode using SetThreadingMode() function.

**Comment by Benedicht** [comment]
`IsThreaded` is a flag to inform the plugin to boot it into threaded mode. It's left in the plugin for backward compatibility, i would recommend to use `CurrentThreadingMode` to check what mode the plugin is in.

**Comment by israellot** [comment]
Yes, I understood that. But the flag can be set after Setup. The semantics
are not very clear.
Anyway, thanks !

**Comment by Benedicht** [comment]
I think i will remove `IsThreaded` in the next release.
