### ISSUE TITLE
can not emit a jsonObject

### ISSUE THREAD

**Issue by HosseinB5017** [Benedicht/BestHTTP_Examples#6]
Hi at first thanks for great plugin
i a'm using socketIO3 and i want to emit a json object and then  i have this erorr
erorr : 
 "JsonException: Max allowed object depth reached while trying to export from type System.Boolean"

here is my client script

[
![image](https://user-images.githubusercontent.com/46160585/215991138-52834372-7a2e-48f9-a370-966c8c3db922.png)
](url)

how can i emit a json with you plugin ?

**Comment by Benedicht** [comment]
`JSONObject` has all kinds of public fields and properties, not just the ones you added through `AddField` and all of them will be converted to json (or at least the json parser will try to convert it, as you experienced it, it throws an exception). You either have to convert your `json` object to a json string and send that (and expect a string on the server side too), or the most easier and straighforward solution is just to use anonymous types:

```cs
var deviceInfo = new
{
    deviceId = SystemInfo.deviceUniqueIdentifier,
    deviceName = SystemInfo.deviceName
};

ConnectionManager.instance.socket.Emit("GetInfoFromDatabase", deviceInfo);
```

**Comment by HosseinB5017** [comment]
thanks for you help its working and i have a another question 
how can i get a json response like this 

   var InfoUser = {
                        UserName : result.recordset[0].UserName,
                        IdTank : result.recordset[0].IdTank,
                        Coin :result.recordset[0].Coin,
                        Cup : result.recordset[0].Cup,
                        WinCount : result.recordset[0].winCount,
                        LoseCount : result.recordset[0].LoseCount,
                        TotalGame : result.recordset[0].TotalGame,
                        IsEditName : result.recordset[0].IsEditName
                    }

i'm using this but not worked 
 ConnectionManager.instance.socket.On<JSONNode>("ResponseGetInfoFromDatabase", ResponseGetInfo);

**Comment by Benedicht** [comment]
It should be something like this:

```cs
// declare a concrete class with all the expected fields
class InfoUser
{
    public string UserName;
    public string IdTank;
    // ...
}

// declare the function with all the expected parameters
void ResponseGetInfo(InfoUser info)
{
    // ...
}

// subscribe to the event
ConnectionManager.instance.socket.On("ResponseGetInfoFromDatabase", ResponseGetInfo);
```

**Comment by HosseinB5017** [comment]
i tried this but i got null data 
how to debug response data ?
![image](https://user-images.githubusercontent.com/46160585/216023998-797c15f0-a379-4bd2-86e0-438d475e1d88.png)

and there is my data object 
![image](https://user-images.githubusercontent.com/46160585/216025459-0eaa8945-1096-4fab-b424-dba5ce78d900.png)

**Comment by Benedicht** [comment]
Forgot the type declaration on the subscription, this is the correct way: `ConnectionManager.instance.socket.On<InfoUser>("ResponseGetInfoFromDatabase", ResponseGetInfo);`

**Comment by HosseinB5017** [comment]
No, I did not forget to put it in the starter in the this script
![image](https://user-images.githubusercontent.com/46160585/216036515-21781576-64ed-4d60-a52f-514548586513.png)

**Comment by Benedicht** [comment]
Made a quick test, this was my server side:
```js
socket.on('GetInfoFromDatabase', (info) => {
    var InfoUser = {
        UserName: "1",
        IdTank: "2",
        Coin: "3",
        Cup: "4",
        WinCount: "5",
        LoseCount: "6",
        TotalGame: "7",
        IsEditName: "8"
    }

    socket.emit('ResponseGetInfoFromDatabase', InfoUser);
});
```

And my previous code from above on the client side, as expected it worked without any issues.

You can set the plugin's logging level to verbose by adding the following line somewhere in your startup code: `BestHTTP.HTTPManager.Logger.Level = BestHTTP.Logger.Loglevels.All;`
Replicate your issue and send over all the log lines. From the logs i might have more clues what happens.
You can read more about logging in the plugin here: https://benedicht.github.io/BestHTTP-Documentation/pages/best_http2/global_topics/Logging.html

**Comment by HosseinB5017** [comment]
{"tid":1,"div":"WebSocketTransport","msg":"OnMessage: 42[\"ResponseGetInfoFromDatabase\",{\"InfoUser\":{\"UserName\":\"hhhhhhs\",\"IdTank\":0,\"Coin\":300,\"Cup\":0,\"WinCount\":0,\"LoseCount\":0,\"TotalGame\":0,\"IsEditName\":true}}]"

here i got data as correctlly but my object is null 

![image](https://user-images.githubusercontent.com/46160585/216042448-69fc26c9-7217-4dc0-bd3f-be3da6af2581.png)

**Comment by Benedicht** [comment]
Do you tried it out with the correct types? The only string you sent is `UserName` while `IdTank`, `Coin`, `Cup`, `WinCount`, `LoseCount` and `TotalGame` are `int`s, `IsEditName` is `bool`:

```cs
class InfoUser
{
    public string UserName;
    public int IdTank;
    public int Coin;
    public int Cup;
    public int WinCount;
    public int LoseCount;
    public int TotalGame;
    public bool IsEditName;
}
```

**Comment by HosseinB5017** [comment]
yeah it's worked 
that was my wrong 
sorry for wasting your time 
thanks for your helping 
i will close this issue
