### ISSUE TITLE
socketIO3 does not work on webgl

### ISSUE THREAD

**Issue by HosseinB5017** [Benedicht/BestHTTP_Examples#7]
hi i 'm using socketio3 
running the sample scene and does not work socketIO3's chat 
but socketIO is worked

![image](https://user-images.githubusercontent.com/46160585/216067795-e7467cdd-792a-4159-b6d4-f4e197dd956e.png)

**Comment by Benedicht** [comment]
The Socket.IO server is the official demo one, hosted by the guys behind socket.io. Their CORS setting allows any site to connect to their service.

On the other hand, the server that the socket.io 3 sample tries to connect to is hosted by me, and its CORS setting allows only the demo page to connect. You can, however run the [server](https://github.com/Benedicht/socket.io3-chat) locally and connect to it.
